# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 02:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='user town')),
                ('street', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='user street')),
                ('house', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='user house')),
                ('appartment', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='user appartment')),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='user phone number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users Detail Model',
                'verbose_name': 'User Detail Model',
            },
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='contractid',
            name='service',
        ),
        migrations.AlterField(
            model_name='contractid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ContractType',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.DeleteModel(
            name='UsersModel',
        ),
    ]
