# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-06 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20171104_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='calc_to_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='to pay 1'),
        ),
    ]
