# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-16 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_payments_calc_to_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(verbose_name='add time')),
                ('user_id', models.CharField(max_length=100, verbose_name='user id')),
                ('msg_source', models.CharField(max_length=100, verbose_name='source')),
                ('msg_type', models.CharField(max_length=100, verbose_name='type')),
                ('msg', models.CharField(max_length=500, verbose_name='msg')),
            ],
            options={
                'verbose_name_plural': 'Logs',
                'verbose_name': 'Log',
            },
        ),
    ]
