# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-23 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20171223_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractid',
            name='user',
        ),
        migrations.RemoveField(
            model_name='countersvalues',
            name='contract',
        ),
        migrations.DeleteModel(
            name='DbInfo',
        ),
        migrations.DeleteModel(
            name='ContractId',
        ),
        migrations.DeleteModel(
            name='CountersValues',
        ),
    ]
