# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-23 21:42
from __future__ import unicode_literals

from django.db import migrations, models

def initial_default_setting(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    DefaultSettingModel = apps.get_model("webapp", "DefaultSettingModel")
    new_item = DefaultSettingModel(
        param = "default_id",
        value = "10023"
    )
    new_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20171223_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSettingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='param')),
                ('value', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='param')),
            ],
            options={
                'verbose_name': 'Default Setting',
                'verbose_name_plural': 'Default Setting',
            },
        ),
        migrations.RunPython(initial_default_setting)
    ]
